on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

name: Release

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        if: ${{ steps.release.outputs['blueprint/yacc--release_created'] }}

      - name: Add File to Release (blueprint/yacc)
        if: ${{ steps.release.outputs['blueprint/yacc--release_created'] }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs['blueprint/yacc--tag_name'] }} blueprint/yacc/yacc.yaml LICENSE
